export const OPEN_CART = 'OPEN_CART';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';
export const CLOSE_CART = 'CLOSE_CART';
export const CLEAR_BASKET = 'CLEAR_BASKET';
